env:
  TERM: xterm-256color
font:
  size: 10
  normal:
    family: "Fira Code"
  use_thin_strokes: true

key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }

cursor:
  style: Underline

dynamic_title: true

live_config_reload: true
